# Generated by Django 5.1 on 2024-08-21 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ruolo', models.CharField(max_length=20)),
                ('prezzo_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('crediti', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_offerta', models.DateTimeField(auto_now_add=True)),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asta.giocatore')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asta.utente')),
            ],
        ),
    ]
