# Generated by Django 5.1 on 2024-08-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asta', '0002_giocatore_rm_giocatore_squadra_alter_giocatore_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giocatore',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='giocatore',
            old_name='prezzo_base',
            new_name='prezzo',
        ),
        migrations.AlterField(
            model_name='utente',
            name='crediti',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
