# Generated by Django 5.1 on 2024-08-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asta', '0003_rename_id_giocatore_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('crediti_iniziali', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
