# Generated by Django 5.1 on 2024-08-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asta', '0005_rename_squadra_giocatore_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giocatore',
            name='prezzoattuale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
